services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
      - DB_USER=$DB_USER
      - DB_NAME=$DB_NAME
      - DB_HOST=$DB_HOST
      - DB_PASS=$DB_PASS
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    env_file:
      - ./back/.env

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:80"

volumes:
  postgres_data:
